
language: csharp
mono: none
dotnet: 2.0

install:
  - dotnet restore src/

script:
  - dotnet build -c Release src/
  - dotnet test src/Rebus.RabbitMq.TransientFaultHelper.Test/Rebus.RabbitMq.TransientFaultHelper.Test.csproj